import datetime

defect_list = ['烧穿', '脱焊', '小焊核', '过烧']
result_list = ['合格', '烧穿', '脱焊', '小焊核', '过烧']

min_fields = ['_id', 'dateTime', 'timerName', 'progNo', 'DAY', 'UMAX', 'IMAX', 'SPLASH_TIME',
               'DATA_SET1_1', 'DATA_SET2_1', 'DATA_SET1_2', 'DATA_SET2_2', 'DATA_SET1_3', 'DATA_SET2_3', 'DATA_SET1_4',
               'DATA_SET2_4', 'DATA_SET1_5', 'DATA_SET2_5', 'DATA_SET1_6', 'DATA_SET2_6', 'DATA_SET1_7', 'DATA_SET2_7',
               'DATA_SET1_8', 'DATA_SET2_8', 'DATA_SET1_9', 'DATA_SET2_9', 'DATA_SET1_10', 'DATA_SET2_10',
               'DATA_SET1_11', 'DATA_SET2_11', 'DATA_SET1_12', 'DATA_SET2_12', 'DATA_SET1_13', 'DATA_SET2_13',
               'DATA_SET1_14', 'DATA_SET2_14', 'DATA_SET1_15', 'DATA_SET2_15', 'DATA_SET1_16', 'DATA_SET2_16',
               'DATA_SET1_17', 'DATA_SET2_17', 'DATA_SET1_18', 'DATA_SET2_18', 'DATA_SET1_19', 'DATA_SET2_19',
               'DATA_SET1_20', 'DATA_SET2_20',
               ]

all_fields = [
    "_id",
    "_class",
    "area",
    "carModel",
    "CUR_CORR_FACTOR",
    "currentActualValue",
    "currentReferenceValue",
    "DATA_SET1_1",
    "DATA_SET1_2",
    "DATA_SET1_3",
    "DATA_SET1_4",
    "DATA_SET1_5",
    "DATA_SET1_6",
    "DATA_SET1_7",
    "DATA_SET1_8",
    "DATA_SET1_9",
    "DATA_SET1_10",
    "DATA_SET1_11",
    "DATA_SET1_12",
    "DATA_SET1_13",
    "DATA_SET1_14",
    "DATA_SET1_15",
    "DATA_SET1_16",
    "DATA_SET1_17",
    "DATA_SET1_18",
    "DATA_SET1_19",
    "DATA_SET1_20",
    "DATA_SET2_1",
    "DATA_SET2_2",
    "DATA_SET2_3",
    "DATA_SET2_4",
    "DATA_SET2_5",
    "DATA_SET2_6",
    "DATA_SET2_7",
    "DATA_SET2_8",
    "DATA_SET2_9",
    "DATA_SET2_10",
    "DATA_SET2_11",
    "DATA_SET2_12",
    "DATA_SET2_13",
    "DATA_SET2_14",
    "DATA_SET2_15",
    "DATA_SET2_16",
    "DATA_SET2_17",
    "DATA_SET2_18",
    "DATA_SET2_19",
    "DATA_SET2_20",
    "dateTime",
    "DAY",
    "DefectConfidence",
    "DefectType",
    "electrodeNo",
    "ENERGIE",
    "energyActualValue",
    "energyRefValue",
    "GUN_RESISTANCE",
    "HOUR",
    "iActual1",
    "iActual2",
    "iActual3",
    "iDemand1",
    "iDemand2",
    "iDemand3",
    "iDemandStd",
    "ilsts",
    "IMAX",
    "MatchType",
    "measureState",
    "measureState_txt",
    "MILLING_COUNTER",
    "MINUTE",
    "monitorMode",
    "monitorMode_txt",
    "monitorState",
    "monitorState_txt",
    "MONTH",
    "NUMBER_OF_DATA",
    "partIdentString",
    "pha1",
    "pha2",
    "pha3",
    "phaStd",
    "PMAX",
    "powerActualValue",
    "powerRefValue",
    "powerState",
    "powerState_txt",
    "progNo",
    "PROGRAM_NUMBER",
    "protRecord_ID",
    "pulseWidthActualValue",
    "pulseWidthRefValue",
    "regulation1",
    "regulation1_txt",
    "regulation2",
    "regulation2_txt",
    "regulation3",
    "regulation3_txt",
    "regulationState",
    "regulationState_txt",
    "regulationStd",
    "regulationStd_txt",
    "resistanceActualValue",
    "resistanceRefValue",
    "SECOND",
    "sequenceRepeat",
    "sequenceRepeat_txt",
    "sequenceState",
    "sequenceState_txt",
    "sequenceStateAdd",
    "sequenceStateAdd_txt",
    "serial",
    "SOFTWARE_VERSION",
    "SPLASH_TIME",
    "spotName",
    "spotTag",
    "stabilisationFactorActValue",
    "stabilisationFactorRefValue",
    "t_iDemandStd",
    "tActualStd",
    "thresholdStabilisationFactor",
    "timerName",
    "tipDressCounter",
    "uipActualValue",
    "uipRefValue",
    "uirExpulsionTime",
    "uirMeasuringActive",
    "uirMeasuringActive_txt",
    "uirMonitoringActive",
    "uirMonitoringActive_txt",
    "uirPsfCondTol",
    "uirPsfLowerTol",
    "uirQStoppActCntValue",
    "uirQStoppRefCntValue",
    "uirRegulationActive",
    "uirRegulationActive_txt",
    "uirUipCondTol",
    "uirUipLowerTol",
    "uirUipUpperTol",
    "uirWeldTimeProlongationActive",
    "uirWeldTimeProlongationActive_txt",
    "UMAX",
    "USER_COMMENT",
    "VERSION_NO",
    "voltageActualValue",
    "voltageRefValue",
    "wear",
    "WEAR_COUNTER",
    "wearPerCent",
    "WeldConfidence",
    "WeldResult",
    "weldTimeActualValue",
    "weldTimeRefValue",
    "wldEffectStabilisationFactor",
    "workStation",
    "WriteTime",
    "YEAR",
    "ZMAX",
    "AB",
    "board1",
    "board2",
    "board3",
    "climbi",
    "climbTime",
    "glueType",
    "gtm",
    "gtm8",
    "gunModel",
    "gunPress",
    "isGlue",
    "prepareTime",
    "pressTime",
    "preWeldCoolTime",
    "preWeldi",
    "preWeldTime",
    "QLScore",
    "Resule_by1",
    "Result_cs",
    "RFID",
    "RFID_1",
    "robot",
    "spotNameExcel",
    "spotNameTimer",
    "thin1",
    "thin2",
    "thin3",
    "wearReplace",
    "weldCoolTime",
    "weldCount",
    "weldHoldTime",
    "weldi",
    "weldTime",
    "workShop",
    "x",
    "y",
    "z",
    "Zero_WeldResult",
    "wearCount",
    "brand",
    "base",
    "model",
    "workshop_section",
    "position",
    "robot_no",
    "spot_id_1",
    "spot_id_2",
    "spot_name",
    "spot_tag",
    "timer_name",
    "prog_no",
    "ABBInfo",
    "car",
    "abb_replace_cap",
    "abb_gun",
    "abb_spot_num",
    "abb_max_sp",
    "abb_wear_times",
    "abb_max_tip_wear",
    "abb_sa_wear_times",
    "abb_ma_wear_times",
    "abb_wear_compensation",
    "abb_x_compensation",
    "abb_z_compensation",
    "abb_pressure_compensation",
    "abb_sp_compensation",
    "splash_score",
]


all_dtype_dict = {
    "_id": str,
    "_class": str,
    "area": str,
    "carModel": str,
    "CUR_CORR_FACTOR": str,
    "currentActualValue": str,
    "currentReferenceValue": str,
    "DATA_SET1_1": str,
    "DATA_SET1_2": str,
    "DATA_SET1_3": str,
    "DATA_SET1_4": str,
    "DATA_SET1_5": str,
    "DATA_SET1_6": str,
    "DATA_SET1_7": str,
    "DATA_SET1_8": str,
    "DATA_SET1_9": str,
    "DATA_SET1_10": str,
    "DATA_SET1_11": str,
    "DATA_SET1_12": str,
    "DATA_SET1_13": str,
    "DATA_SET1_14": str,
    "DATA_SET1_15": str,
    "DATA_SET1_16": str,
    "DATA_SET1_17": str,
    "DATA_SET1_18": str,
    "DATA_SET1_19": str,
    "DATA_SET1_20": str,
    "DATA_SET2_1": str,
    "DATA_SET2_2": str,
    "DATA_SET2_3": str,
    "DATA_SET2_4": str,
    "DATA_SET2_5": str,
    "DATA_SET2_6": str,
    "DATA_SET2_7": str,
    "DATA_SET2_8": str,
    "DATA_SET2_9": str,
    "DATA_SET2_10": str,
    "DATA_SET2_11": str,
    "DATA_SET2_12": str,
    "DATA_SET2_13": str,
    "DATA_SET2_14": str,
    "DATA_SET2_15": str,
    "DATA_SET2_16": str,
    "DATA_SET2_17": str,
    "DATA_SET2_18": str,
    "DATA_SET2_19": str,
    "DATA_SET2_20": str,
    "dateTime": str,
    "DAY": str,
    "DefectConfidence": str,
    "DefectType": str,
    "electrodeNo": int,
    "ENERGIE": float,
    "energyActualValue": float,
    "energyRefValue": float,
    "GUN_RESISTANCE": int,
    "HOUR": int,
    "iActual1": float,
    "iActual2": float,
    "iActual3": float,
    "iDemand1": float,
    "iDemand2": float,
    "iDemand3": float,
    "iDemandStd": float,
    "ilsts": float,
    "IMAX": float,
    "MatchType": str,
    "measureState": int,
    "measureState_txt": str,
    "MILLING_COUNTER": int,
    "MINUTE": int,
    "monitorMode": int,
    "monitorMode_txt": str,
    "monitorState": int,
    "monitorState_txt": str,
    "MONTH": int,
    "NUMBER_OF_DATA": int,
    "partIdentString": str,
    "pha1": float,
    "pha2": float,
    "pha3": float,
    "phaStd": float,
    "PMAX": float,
    "powerActualValue": float,
    "powerRefValue": float,
    "powerState": int,
    "powerState_txt": str,
    "progNo": int,
    "PROGRAM_NUMBER": int,
    "protRecord_ID": int,
    "pulseWidthActualValue": float,
    "pulseWidthRefValue": float,
    "regulation1": int,
    "regulation1_txt": str,
    "regulation2": int,
    "regulation2_txt": str,
    "regulation3": int,
    "regulation3_txt": str,
    "regulationState": int,
    "regulationState_txt": str,
    "regulationStd": int,
    "regulationStd_txt": str,
    "resistanceActualValue": float,
    "resistanceRefValue": float,
    "SECOND": int,
    "sequenceRepeat": int,
    "sequenceRepeat_txt": str,
    "sequenceState": int,
    "sequenceState_txt": str,
    "sequenceStateAdd": int,
    "sequenceStateAdd_txt": str,
    "serial": str,
    "SOFTWARE_VERSION": str,
    "SPLASH_TIME": float,
    "spotName": str,
    "spotTag": str,
    "stabilisationFactorActValue": float,
    "stabilisationFactorRefValue": float,
    "t_iDemandStd": float,
    "tActualStd": float,
    "thresholdStabilisationFactor": float,
    "timerName": str,
    "tipDressCounter": int,
    "uipActualValue": float,
    "uipRefValue": float,
    "uirExpulsionTime": float,
    "uirMeasuringActive": int,
    "uirMeasuringActive_txt": str,
    "uirMonitoringActive": int,
    "uirMonitoringActive_txt": str,
    "uirPsfCondTol": float,
    "uirPsfLowerTol": float,
    "uirQStoppActCntValue": float,
    "uirQStoppRefCntValue": float,
    "uirRegulationActive": int,
    "uirRegulationActive_txt": str,
    "uirUipCondTol": float,
    "uirUipLowerTol": float,
    "uirUipUpperTol": float,
    "uirWeldTimeProlongationActive": int,
    "uirWeldTimeProlongationActive_txt": str,
    "UMAX": float,
    "USER_COMMENT": str,
    "VERSION_NO": str,
    "voltageActualValue": float,
    "voltageRefValue": float,
    "wear": float,
    "WEAR_COUNTER": int,
    "wearPerCent": float,
    "WeldConfidence": str,
    "WeldResult": str,
    "weldTimeActualValue": float,
    "weldTimeRefValue": float,
    "wldEffectStabilisationFactor": float,
    "workStation": str,
    "WriteTime": str,
    "YEAR": int,
    "ZMAX": float,
    "AB": str,
    "board1": str,
    "board2": str,
    "board3": str,
    "climbi": str,
    "climbTime": str,
    "glueType": str,
    "gtm": datetime.datetime,
    "gtm8": datetime.datetime,
    "gunModel": str,
    "gunPress": float,
    "isGlue": str,
    "prepareTime": float,
    "pressTime": float,
    "preWeldCoolTime": float,
    "preWeldi": float,
    "preWeldTime": float,
    "QLScore": float,
    "Resule_by1": str,
    "Result_cs": str,
    "RFID": str,
    "RFID_1": str,
    "robot": str,
    "spotNameExcel": str,
    "spotNameTimer": str,
    "thin1": float,
    "thin2": float,
    "thin3": float,
    "wearReplace": float,
    "weldCoolTime": float,
    "weldCount": float,
    "weldHoldTime": float,
    "weldi": float,
    "weldTime": float,
    "workShop": str,
    "x": float,
    "y": float,
    "z": float,
    "Zero_WeldResult": str,
    "wearCount": int,
    "brand": str,
    "base": str,
    "model": str,
    "workshop_section": str,
    "position": str,
    "robot_no": str,
    "spot_id_1": str,
    "spot_id_2": str,
    "spot_name": str,
    "spot_tag": str,
    "timer_name": str,
    "prog_no": int,
    "ABBInfo": str,
    "car": int,
    "abb_replace_cap": int,
    "abb_gun": str,
    "abb_spot_num": int,
    "abb_max_sp": float,
    "abb_wear_times": float,
    "abb_max_tip_wear": float,
    "abb_sa_wear_times": float,
    "abb_ma_wear_times": float,
    "abb_wear_compensation": float,
    "abb_x_compensation": float,
    "abb_z_compensation": float,
    "abb_pressure_compensation": float,
    "abb_sp_compensation": float,
    "splash_score":float,
}
